site_name: bespoken.tools
repo_url: https://github.com/bespoken/bst
site_dir: 'site'
strict: true
pages:
- Home: index.md
- Getting Started: getting_started.md
- Alexa Skill Configuration: alexa_skills_kit_configuration.md
- Commands:
    - bst proxy: commands/proxy.md
    - bst speak: commands/speak.md
- API Reference: api/index.html
- Tutorials:
    - Nodejs Lambda: tutorials/tutorial_lambda_nodejs.md
    - Local Java Server: tutorials/tutorial_local_server_java.md
    - Python & Flask-Ask: tutorials/tutorial_flask_ask_python.md
    - Alexa Emulator & Nodejs: tutorials/tutorial_bst_emulator_nodejs.md
theme: readthedocs
markdown_extensions:
- attr_list
extra_css: [assets/css/style.css]
